/* This file was generated by ConfigHeader using the Zig Build System. */
#ifndef CONFIG_H
#define CONFIG_H
#define OPUS_X86_MAY_HAVE_SSE 1
#define OPUS_X86_MAY_HAVE_SSE2 1
#define OPUS_X86_MAY_HAVE_SSE4_1 1
#define OPUS_X86_PRESUME_SSE 1
#define OPUS_X86_PRESUME_SSE2 1
#define OPUS_X86_PRESUME_SSE4_1 1
#endif /* CONFIG_H */
